# Generated by Django 4.2.4 on 2023-08-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_establecimiento', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('cp', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150)),
                ('provincia', models.CharField(max_length=150)),
                ('persona_contacto', models.CharField(max_length=150)),
                ('telefono_contacto', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('sector_actividad', models.CharField(max_length=150)),
                ('tipo_terminal', models.CharField(choices=[('N/A', 'N/A'), ('CAJERO', 'CAJERO'), ('DATAFONO', 'DATAFONO')], max_length=10)),
                ('comision', models.IntegerField()),
                ('retorno', models.CharField(choices=[('N/A', 'N/A'), ('SI', 'SI'), ('NO', 'NO')], max_length=3)),
                ('fondo_inicial', models.IntegerField()),
                ('aportacion_fondo', models.CharField(choices=[('N/A', 'N/A'), ('CLIENTE', 'CLIENTE'), ('NOSOTROS', 'NOSOTROS')], max_length=10)),
                ('metodo_reposicion', models.CharField(choices=[('N/A', 'N/A'), ('CLIENTE', 'CLIENTE'), ('NOSOTROS', 'NOSOTROS')], max_length=15)),
            ],
        ),
    ]
